services:
  - type: web
    name: notebooklm-backend
    env: python
    plan: free
    autoDeploy: true
    rootDir: notebookLM-backend
    buildCommand: |
      python --version
      pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PIP_ONLY_BINARY
        value: "PyMuPDF"
      - key: DEBUG
        value: "false"
